### PR TITLE
Build with Bazel

### PR DESCRIPTION
**Pull request by patrickt**
Ready for review!

Blockers: 
- [x] Figure out how to specify `-O0` and `-fdiagnostics-color` only when building on the CLI.
- [x] Stop hard-coding the path to the JSON files
- [x] Finish applying `bazel-runfiles` stuff to the tests
- [x] Write a shim over `bazel-runfiles` that makes sure calls to `runfiles` are no-opped if you’re running under Cabal
- [x] Write some docs/cheatsheets
- [x] Rename shared variables
- [x] Fix `parse-examples` target
- [x] Fix the languages’ parsing tests.

Nice to have:
- [x] https://github.com/tweag/rules_haskell/issues/1377 means that running the language packages’ `@repl` targets don’t work
- [ ] Figure out how to ensure that ghcide doesn’t try to emit color output when it fails.
- [x] Trim some of the deps we don’t use anymore (in cabal too)
- [x] Shared macro for declaring language packages
- [x] Use `git_repository` or `http_archive` to download the node-types.json files rather than embedding them manually
- [x] Backport moving src and test into a different patch
- [x] Do some switcheroos with `hie.yaml` so that the tooling doesn’t break for non-bazel users
- [ ] Figure out how to stamp version/SHA info—can we do that with `haskell_binary`?
- [ ] Get the `pretty-simple` invocation in `.ghci` right/configure it correctly

To investigate:
- [ ] building tree-sitter packages with Bazel—couldn’t figure out linker errors there
- [x] rethink `lingo` generation
- [ ] a zero-wait REPL a la `script/repl`
- [ ] scripting?

Related bugs:
* https://github.com/tweag/rules_haskell/issues/1337
* https://github.com/tweag/rules_haskell/issues/1246

### CODE REVIEW

**Comment by joshvera** [comment]
Running into an error with `bazel build //...`

<details>

```shell


➜  semantic-8.10 git:(bazel-experiments) bazel build //...
INFO: Invocation ID: 20e26d8c-abb8-4d76-aca0-42a5d681f94e
DEBUG: Rule 'tree-sitter-php' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1591381188 -0400"
DEBUG: Repository tree-sitter-php instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule new_git_repository defined at:
  /private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/external/bazel_tools/tools/build_defs/repo/git.bzl:182:37: in <toplevel>
DEBUG: Rule 'moby' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1533485518 -0700"
DEBUG: Repository moby instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule new_git_repository defined at:
  /private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/external/bazel_tools/tools/build_defs/repo/git.bzl:182:37: in <toplevel>
DEBUG: Rule 'golang' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1533564744 +0000"
DEBUG: Repository golang instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule new_git_repository defined at:
  /private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/external/bazel_tools/tools/build_defs/repo/git.bzl:182:37: in <toplevel>
INFO: Analyzed 87 targets (10 packages loaded, 9928 targets configured).
INFO: Found 87 targets...
ERROR: /private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/external/stackage/BUILD.bazel:1425:22: HaskellCabalLibrary @stackage//:primitive failed (Exit 1) cabal_wrapper failed: error executing command bazel-out/host/bin/external/rules_haskell/haskell/cabal_wrapper lib:primitive primitive-0.7.0.1 true external/stackage/primitive-0.7.0.1/Setup.hs external/stackage/primitive-0.7.0.1 ... (remaining 6 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Setup.hs: Missing dependency on a foreign library:
* Missing (or bad) header file: primitive-memops.h
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.If the
library file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
If the header file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.

Traceback (most recent call last):
  File "/private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/sandbox/darwin-sandbox/19/execroot/semantic/bazel-out/host/bin/external/rules_haskell/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 138, in <module>
    run([runghc, setup, "configure", \
  File "/private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/sandbox/darwin-sandbox/19/execroot/semantic/bazel-out/host/bin/external/rules_haskell/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 42, in run
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, *args, **kwargs)
  File "/Users/vera/.pyenv/versions/3.8.2/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/sandbox/darwin-sandbox/19/execroot/semantic/external/rules_haskell_ghc_darwin_amd64/bin/runghc', '/private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/sandbox/darwin-sandbox/19/execroot/semantic/external/stackage/primitive-0.7.0.1/Setup.hs', 'configure', 'lib:primitive', '--verbose=0', '--user', '--with-compiler=/private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/sandbox/darwin-sandbox/19/execroot/semantic/external/rules_haskell_ghc_darwin_amd64/bin/ghc', '--with-hc-pkg=/private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/sandbox/darwin-sandbox/19/execroot/semantic/external/rules_haskell_ghc_darwin_amd64/bin/ghc-pkg', '--with-ar=/usr/bin/ar', '--with-gcc=/private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/sandbox/darwin-sandbox/19/execroot/semantic/bazel-out/host/bin/external/rules_haskell/haskell/cc_wrapper-python', '--with-strip=/usr/bin/strip', '--enable-deterministic', '--enable-relocatable', '--builddir=/var/folders/hv/h_xs5ydn4g9039p579xnyvg00000gn/T/tmpwiglhm3t', '--prefix=/private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/sandbox/darwin-sandbox/19/execroot/semantic/bazel-out/darwin-fastbuild/bin/external/stackage/primitive-0.7.0.1/_install', '--libdir=/private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/sandbox/darwin-sandbox/19/execroot/semantic/bazel-out/darwin-fastbuild/bin/external/stackage/primitive-0.7.0.1/_install/primitive-0.7.0.1_iface', '--dynlibdir=/private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/sandbox/darwin-sandbox/19/execroot/semantic/bazel-out/darwin-fastbuild/bin/external/stackage/primitive-0.7.0.1/_install/lib', '--libsubdir=', '--bindir=/private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/sandbox/darwin-sandbox/19/execroot/semantic/bazel-out/darwin-fastbuild/bin/external/stackage/primitive-0.7.0.1/_install/bin', '--datadir=/private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/sandbox/darwin-sandbox/19/execroot/semantic/bazel-out/darwin-fastbuild/bin/external/stackage/primitive-0.7.0.1/_install/primitive-0.7.0.1_data', '--datasubdir=', '--haddockdir=/private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/sandbox/darwin-sandbox/19/execroot/semantic/bazel-out/darwin-fastbuild/bin/external/stackage/primitive-0.7.0.1/_install/primitive-0.7.0.1_haddock', '--htmldir=/private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/sandbox/darwin-sandbox/19/execroot/semantic/bazel-out/darwin-fastbuild/bin/external/stackage/primitive-0.7.0.1/_install/primitive-0.7.0.1_haddock_html', '--package-db=clear', '--package-db=global', '--flags=', '--ghc-option=-w', '--ghc-option=-optF=-w', '--with-happy=/private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/sandbox/darwin-sandbox/19/execroot/semantic/bazel-out/host/bin/external/happy/_install/bin/happy', '--package-db=/private/var/tmp/_bazel_vera/d3aa5c84aa6702ce8cce45359dfd1c71/sandbox/darwin-sandbox/19/execroot/semantic/bazel-out/darwin-fastbuild/bin/external/stackage/primitive-0.7.0.1/_install/primitive-0.7.0.1.conf.d']' returned non-zero exit status 1.
INFO: Elapsed time: 34.208s, Critical Path: 4.72s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

```

</details>

**Comment by patrickt** [comment]
@joshvera Hmm, I haven’t seen that one before, I’m afraid. I’m booting up my old laptop to see if I can reproduce.

**Comment by patrickt** [comment]
@joshvera Try `export BAZEL_USE_CPP_ONLY_TOOLCHAIN=1` then rebuild?

**Comment by Profpatsch** [comment]
This is amazing @patrickt, feels great to have our work powering semantic!

**Comment by robrix** [comment]
🎉

**Pull request merged**
