### PR TITLE
Add `.mjs` as extension for JavaScript

### PR DESCRIPTION
**Pull request by devsnek**

### CODE REVIEW

**Comment by robrix** [comment]
@devsnek: Thanks for the PR! Could you provide me with some details for .mjs files, e.g. where/when do they occur, what tools read/write/expect them, do they contain “regular” JavaScript or some dialect thereof, etc., please? 🙏

**Comment by shiftkey** [comment]
@robrix `.mjs` files are JS files that are explicitly compatible with the ES module loader (rather than the CommonJS module loader). Ideally we wouldn't need to rename the file extension to opt-in for this new behaviour, but because of how broad the ecosystem is they settled on this process as a way to transition the ecosystem to this new module loader.

Some other links:

 - [ES modules: A cartoon deep-dive](https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/]
 - [Differences Between ES Modules and CommonJS](https://nodejs.org/api/esm.html#esm_differences_between_es_modules_and_commonjs)
 - [Files with .mjs extension for JavaScript modules](https://medium.com/passpill-project/files-with-mjs-extension-for-javascript-modules-ced195d7c84a)

**Comment by devsnek** [comment]
The files should contain only ecmascript module syntax (strict mode, import/export, no html comments, etc), but I suspect your parser doesn't care about stuff like that.

Google, Mozilla, and GoDaddy are also working to register this extension with the IETF: https://datatracker.ietf.org/doc/draft-ietf-dispatch-javascript-mjs/

**Comment by robrix** [comment]
Thanks for the context @shiftkey & @devsnek! I’ve also dug up plenty of .mjs files in GitHub repos, and [`linguist` treats it as JS](https://github.com/github/linguist/blob/33a9ba2505e7be9b2b39de38e6954dfd60b0483b/lib/linguist/languages.yml#L2418) too. I am delighted to merge this, thank you 😊

**Comment by devsnek** [comment]
out of curiosity, is there any timeline on this being deployed such that i can use "jump to definition" in mjs files?

**Comment by patrickt** [comment]
@devsnek We need to bump internal services to depend on this new code. It should happen soon.

**Pull request merged**
